g++ -O3 -Wall -Wextra -pedantic ./src/initial.cpp -o ./build/initial
g++ -O3 -Wall -Wextra -pedantic ./src/wReserve.cpp -o ./build/wReserve
g++ -O3 -Wall -Wextra -pedantic ./src/wEncode.cpp -o ./build/wEncode
g++ -O3 -Wall -Wextra -pedantic ./src/wCustomString.cpp -o ./build/wCustomString
g++ -O3 -Wall -Wextra -pedantic ./src/wModuleOpt.cpp -o ./build/wModuleOpt
g++ -O3 -Wall -Wextra -pedantic ./src/wLoopUnroll.cpp -o ./build/wLoopUnroll
g++ -O3 -Wall -Wextra -pedantic ./src/wToString.cpp -o ./build/wToString
g++ -O3 -Wall -Wextra -pedantic ./src/wToString2.cpp -o ./build/wToString2
g++ -O3 -Wall -Wextra -pedantic ./src/wToString3.cpp -o ./build/wToString3
g++ -O3 -Wall -Wextra -pedantic ./src/wMultiThread.cpp -o ./build/wMultiThread